vich_uploader:
    db_driver: orm

    metadata:
        auto_detection: true
        cache: file
        type: attribute 
    mappings:
    #    repairs:
    #         uri_prefix: '%app.path.repairs_images%'
    #         upload_destination: '%kernel.project_dir%/public%app.path.repairs_images%'
    #         namer: Vich\UploaderBundle\Naming\OrignameNamer
    #         delete_on_update: true
    #         inject_on_load: false 
       worksites:
            uri_prefix: '%app.path.worksites_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.worksites_images%'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            delete_on_update: true
            inject_on_load: false